apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-apache
  template:
    metadata:
      labels:
        app: my-app-apache
    spec:
      containers:
        - name: my-app-apache
          image: httpd:latest
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "APACHE APP"
---